// Jack King's Classic 2026 — competitor + class data.
// Source of truth: the promoter's CSV. Number 46 intentionally withdrew — do not fill the gap.
const COMPETITORS = [
  { n: 11, name: "Nick Athan", cat: "Men's Bodybuilding" },
  { n: 12, name: "Jamal Wallington", cat: "Men's Bodybuilding" },
  { n: 13, name: "Aaron Freeman", cat: "Men's Physique" },
  { n: 14, name: "Tyson Merritt", cat: "Men's Physique" },
  { n: 15, name: "Victor Oyinwola", cat: "Men's Physique" },
  { n: 16, name: "Stephen Hinton", cat: "Men's Physique" },
  { n: 17, name: "Carlos Williams", cat: "Men's Physique" },
  { n: 18, name: "Kareem Lewis", cat: "Men's Physique" },
  { n: 19, name: "Jacob Bunton", cat: "Men's Physique" },
  { n: 20, name: "Chuck Dixon", cat: "Men's Physique" },
  { n: 21, name: "Phillip Snyder", cat: "Men's Physique" },
  { n: 22, name: "Jarrett Love", cat: "Men's Physique" },
  { n: 23, name: "Damien Smith", cat: "Men's Physique" },
  { n: 24, name: "Gage Parks", cat: "Men's Physique" },
  { n: 25, name: "Davonte Ruffin", cat: "Men's Physique" },
  { n: 26, name: "Mason Yarbray", cat: "Men's Physique" },
  { n: 27, name: "Michael Foster", cat: "Men's Physique" },
  { n: 28, name: "Hassan Shaheed", cat: "Men's Physique" },
  { n: 29, name: "Nemy Eban-Siu", cat: "Men's Physique" },
  { n: 30, name: "Joseph Krause", cat: "Men's Physique" },
  { n: 31, name: "Sharodd Clayborne", cat: "Men's Physique" },
  { n: 32, name: "Wyatt Spitz", cat: "Men's Classic Physique" },
  { n: 33, name: "Riccardo Scichilone", cat: "Men's Classic Physique" },
  { n: 34, name: "Joshua Edwards", cat: "Men's Classic Physique" },
  { n: 35, name: "John Hennegan", cat: "Men's Classic Physique" },
  { n: 36, name: "Joshua Cox", cat: "Men's Classic Physique" },
  { n: 37, name: "Zachary Titus", cat: "Men's Classic Physique" },
  { n: 38, name: "Andrew Inserillo", cat: "Men's Classic Physique" },
  { n: 39, name: "Eddie Baker", cat: "Men's Classic Physique" },
  { n: 40, name: "Peter Herman", cat: "Men's Classic Physique" },
  { n: 41, name: "Aaron Rorabaugh", cat: "Men's Classic Physique" },
  { n: 42, name: "Karsten Woodard", cat: "Men's Classic Physique" },
  { n: 43, name: "Stone Brisson", cat: "Men's Classic Physique" },
  { n: 44, name: "Ryan Kelly", cat: "Men's Classic Physique" },
  { n: 45, name: "Joseph Cook", cat: "Men's Classic Physique" },
  { n: 47, name: "Ally Alexander", cat: "Women's Physique" },
  { n: 48, name: "Tessica Byers", cat: "Women's Physique" },
  { n: 49, name: "Pamela Callahan", cat: "Women's Figure" },
  { n: 50, name: "Marcy Welch", cat: "Women's Figure" },
  { n: 51, name: "Megan Lawson", cat: "Women's Figure" },
  { n: 52, name: "Hannah Woody", cat: "Women's Figure" },
  { n: 53, name: "Caleigh Robinson", cat: "Women's Figure" },
  { n: 54, name: "Izabela Atwell", cat: "Women's Bikini" },
  { n: 55, name: "Jessica Swaim", cat: "Women's Bikini" },
  { n: 56, name: "Yaharena Guerra", cat: "Women's Bikini" },
  { n: 57, name: "Alyssa McCraw", cat: "Women's Bikini" },
  { n: 58, name: "Ebony Scott", cat: "Women's Bikini" },
  { n: 59, name: "Andrea Hutchinson", cat: "Women's Bikini" },
  { n: 60, name: "Aman Rivas", cat: "Women's Bikini" },
  { n: 61, name: "Kellianne Dempsey", cat: "Women's Bikini" },
  { n: 62, name: "Chloe Adams", cat: "Women's Bikini" },
  { n: 63, name: "Emily Rollins", cat: "Women's Wellness" },
  { n: 64, name: "Margot Nazario", cat: "Women's Wellness" },
  { n: 65, name: "Jessica Toache Rubio", cat: "Women's Wellness" },
  { n: 66, name: "Daphni Barwick", cat: "Women's Wellness" },
];

// Running order confirmed by the promoter, 2026-07-15. Names render exactly as written.
const CLASSES = [
  { name: "Men's Bodybuilding Debut", nums: [12] },
  { name: "Men's Bodybuilding Novice", nums: [12] },
  { name: "Men's Bodybuilding 60+", nums: [11] },
  { name: "Men's Bodybuilding Open PQ", nums: [12] },
  { name: "Men's Physique Debut A", nums: [13, 14, 28, 29] },
  { name: "Men's Physique Debut B", nums: [19, 20, 21, 30] },
  { name: "Men's Physique Novice A", nums: [14, 26, 28, 29] },
  { name: "Men's Physique Novice B", nums: [21, 22, 24, 31] },
  { name: "Men's Physique Novice C", nums: [17, 19, 27, 30] },
  { name: "Men's Physique 40+ PQ", nums: [16, 18, 21, 23] },
  { name: "Men's Physique 50+", nums: [16, 23] },
  { name: "Men's Physique Open A PQ", nums: [13, 16, 18, 25, 26, 29] },
  { name: "Men's Physique Open B PQ", nums: [14, 17, 21, 22, 24, 28] },
  { name: "Men's Physique Open C PQ", nums: [15, 19, 23, 27, 30] },
  { name: "Men's Classic Physique Debut A", nums: [32, 36, 41, 42] },
  { name: "Men's Classic Physique Debut B", nums: [37, 38, 43, 45] },
  { name: "Men's Classic Physique Novice A", nums: [33, 34, 36] },
  { name: "Men's Classic Physique Novice B", nums: [38, 42, 43] },
  { name: "Men's Classic Physique 40+ PQ", nums: [38, 39] },
  { name: "Men's Classic Physique Open A PQ", nums: [32, 33, 34, 35, 36] },
  { name: "Men's Classic Physique Open B PQ", nums: [38, 40, 43, 44, 45] },
  { name: "Women's Physique Debut", nums: [48] },
  { name: "Women's Physique Novice", nums: [47, 48] },
  { name: "Women's Physique Open PQ", nums: [47] },
  { name: "Women's Figure Debut", nums: [52] },
  { name: "Women's Figure Novice", nums: [52] },
  { name: "Women's Figure 40+ PQ", nums: [49, 51] },
  { name: "Women's Figure 50+", nums: [49] },
  { name: "Women's Figure 60+", nums: [50] },
  { name: "Women's Figure Open PQ", nums: [49, 50, 51, 52, 53] },
  { name: "Women's Bikini Debut", nums: [56, 57, 59, 61] },
  { name: "Women's Bikini Novice A", nums: [56, 57, 60, 61] },
  { name: "Women's Bikini Novice B", nums: [54, 55, 58, 59] },
  { name: "Women's Bikini 40+ PQ", nums: [54, 60] },
  { name: "Women's Bikini Open PQ", nums: [55, 56, 57, 58, 59, 61, 62] },
  { name: "Women's Wellness Debut", nums: [63, 64] },
  { name: "Women's Wellness Novice", nums: [63, 64, 65, 66] },
  { name: "Women's Wellness 40+ PQ", nums: [65, 66] },
  { name: "Women's Wellness Open PQ", nums: [63, 64, 66] },
];

// One-line "what judges look for" per division, condensed from ocbonline.com's category pages.
const DIVISION_INFO = {
  "Men's Bodybuilding": {
    desc: "The most muscular, developed, and lean of the men's categories — judged on symmetry, size, and definition, with deep cuts and striations on full display.",
    url: "https://ocbonline.com/mens-bodybuilding/",
  },
  "Men's Physique": {
    desc: "A lean, V-tapered upper body presented in board shorts — wide back, small waist, etched abs. Extreme size and conditioning are intentionally avoided here.",
    url: "https://ocbonline.com/mens-physique/",
  },
  "Men's Classic Physique": {
    desc: "A nod to the classic era: balance and proportion take precedence over sheer size, with less extreme leanness than open bodybuilding.",
    url: "https://ocbonline.com/mens-classic-physique/",
  },
  "Women's Physique": {
    desc: "The most muscular of the women's categories — a feminine, balanced look with a high degree of muscularity and the leanest conditioning on the women's side.",
    url: "https://ocbonline.com/womens-physique/",
  },
  "Women's Figure": {
    desc: "Judged on symmetry, muscularity, and conditioning — an X-frame with capped shoulders, wide back, small waist, and visible muscle separation.",
    url: "https://ocbonline.com/figure/",
  },
  "Women's Bikini": {
    desc: "A healthy, toned, hourglass look with balance, shape, and proportion — lightly muscled by design, and the only category judged on a stage walk.",
    url: "https://ocbonline.com/bikini/",
  },
  "Women's Wellness": {
    desc: "The one category where upper/lower symmetry isn't the goal — a dominant, muscular lower body with full glutes and sweeping quads, paired with a lighter upper body.",
    url: "https://ocbonline.com/womens-wellness/",
  },
};

// Day-of results. Key = exact class name, value = competitor numbers in placement
// order (1st, 2nd, 3rd, ...). Filled in live during the show; empty until then.
const RESULTS = {
};

const EVENT = {
  title: "OCB Jack King's Classic 2026",
  date: "Saturday, July 18, 2026",
  venue: "Winston-Salem State Anderson Center",
  address: "1545 Reynolds Park Rd, Winston-Salem, NC 27101",
  mapsUrl: "https://maps.google.com/?q=Anderson+Center,+1545+Reynolds+Park+Rd,+Winston-Salem,+NC+27101",
  doors: "Doors 9:00 AM",
  mens: "Show starts 10:00 AM",
  womens: "Women's show 1:00 PM",
  foodTruck: "Curbing UR Appetite food truck on site 10:30 AM – 2:00 PM",
  cornhole: "Play cornhole throughout the show — win prizes at the King's Advantage vendor table.",
  launch: "King's Advantage launch party — giveaways at the vendor table all day.",
  tagline: "Tag your athlete photos",
  social: "@ocbjackkingsclassic",
  socialUrl: "https://www.instagram.com/ocbjackkingsclassic",
};

const SPONSORS = {
  title: {
    name: "King's Advantage",
    sub: "Elite Nutrition — Title Sponsor",
    img: "assets/logos/web/kings-advantage.png",
    url: "https://www.instagram.com/kings_advantage_nutrition",
  },
  vendors: [
    {
      name: "Mammoth Nutrition",
      img: "assets/logos/web/mammoth-nutrition.png",
      url: "https://www.instagram.com/mammoth.nutrition",
    },
    {
      name: "Greg's Muffins",
      img: "assets/logos/web/gregs-muffins.svg",
      url: "https://www.instagram.com/greg.partin1",
    },
    {
      name: "Viva Barista Cafe",
      sub: "Coffee roastery — the owner is competing today!",
      img: "assets/logos/web/viva-barista.png",
      url: "https://www.instagram.com/vivabaristacafe",
    },
    {
      name: "Curbing UR Appetite",
      sub: "Food truck · 10:30 AM – 2:00 PM",
      img: null,
      url: null,
    },
  ],
  host: {
    name: "Jack King's Gym",
    img: "assets/logos/web/jack-kings-gym.png",
    url: "https://www.instagram.com/jackkingsgym",
  },
};
